require:
  - rubocop-rails

AllCops:
  TergetRubyVersion: 2.7.2
  Exclude:
    - '**/db/**/*'
    - 'config/**/*'
    - 'bin/*'
    - 'config.ru'

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Lint/UnusedMethodArgument:
  Enabled: false

Lint/ParenthesesAsGroupedExpression:
  Enabled: false

Layout/LeadingCommentSpace:
  Enabled: false

Layout/TrailingWhitespace:
  Enabled: false

Layout/IndentationWidth:
  Enabled: false

Layout/CommentIndentation:
  Enabled: false

Layout/TrailingEmptyLines:
  Enabled: false

Layout/EmptyComment:
  Enabled: false

Style/GuardClause:
  Enabled: false

Layout/SpaceInsidePercentLiteralDelimiters:
  Enabled: false

Rails/LexicallyScopedActionFilter:
  Enabled: false


